PromptL compiler v1 - Chapter 2: Content tags and tool calls
latitude-dev/latitude-llm pull request #565
Opened 2024-11-07 10:10 UTC by csansoon

2024-11-09 09:30 UTC, andresgutgon commented on packages/promptl/src/parser/state/mustache.test.ts
> -}
So much dry. Nice

2024-11-09 09:32 UTC, andresgutgon commented on pnpm-lock.yaml
Why so many changes? I don't see any change in `package.json`?

2024-11-09 09:32 UTC, andresgutgon requested changes
Review why `pnpm-lock.yaml` has so many changes and 👍

2024-11-11 08:49 UTC, csansoon commented on pnpm-lock.yaml
My vscode prettified it lol

2024-11-11 08:54 UTC, merged

2024-11-11 08:57 UTC, geclos commented
> However, we’ll introduce an automatic adapter in a future PR

hmm thinking about this it might be worth making these adapters as external packages and have the compiler accept custom adapters, so that we can leverage the community to build their own adapters for other providers since I'm sure we won't be able to support all edge cases for all providers out of the box. The adapters should be pure functions that receive a particular input from the compiler that is always the same, and output whatever the provider they target requires. 

It's also important that these adapters are as decoupled from the compiler internals as possible, in order to reduce the barrier of entry for developers.